parser: babel-eslint

plugins:
  # - import
  # - react
  # - jsx-a11y
  - flowtype
  - prettier
  - react-hooks

extends:
  - airbnb
  - prettier

env:
  browser: true

rules:
  prettier/prettier:
    - error

  max-classes-per-file: off
  consistent-return: off
  react/jsx-one-expression-per-line: off
  react/jsx-props-no-spreading: off
  react/prop-types: off
  react/destructuring-assignment: off
  react/jsx-closing-bracket-location: off

  # arrow-parens: off
  # arrow-spacing: off
  # block-spacing: off
  # brace-style: off
  # comma-dangle: off
  # comma-spacing: off
  # curly: off
  # function-paren-newline: off
  # implicit-arrow-linebreak: off
  # indent: off
  # key-spacing: off
  # keyword-spacing: off
  # max-len: off
  # new-parens: off
  # no-confusing-arrow: off
  # no-multi-spaces: off
  # no-multiple-empty-lines: off
  # no-trailing-spaces: off
  # no-undef: off
  # no-unused-expressions: off
  # no-use-before-define: off
  # nonblock-statement-body-position: off
  # object-curly-newline: off
  # object-curly-spacing: off
  # object-property-newline: off
  # operator-linebreak: off
  # padded-blocks: off
  # quote-props: off
  # semi: off
  # space-infix-ops: off

  # import/prefer-default-export: off

  # jsx-quotes: off

  # jsx-a11y/anchor-is-valid: off
  # jsx-a11y/no-autofocus: off

  # react/destructuring-assignment: off
  # react/jsx-closing-bracket-location: off
  # react/jsx-closing-tag-location: off
  # react/jsx-curly-newline: off
  # react/jsx-equals-spacing: off
  # react/jsx-first-prop-new-line: off
  # react/jsx-indent-props: off
  # react/jsx-indent: off
  # react/jsx-max-props-per-line: off
  # react/jsx-one-expression-per-line: off
  # react/jsx-props-no-multi-spaces: off
  # react/jsx-props-no-spreading: off
  # react/jsx-tag-spacing: off
  # react/jsx-wrap-multilines: off
  # react/prop-types: off
  # react/self-closing-comp: off
  # react/style-prop-object: off

  import/prefer-default-export: off

  no-use-before-define: off

  eqeqeq: [error, smart]
  no-dupe-keys: error
  prefer-destructuring: error
  no-shadow-restricted-names: error
  no-unused-vars:
    - error
    - vars: all
      varsIgnorePattern: ^(_|(omit|ignore)[0-9]+)$
      args: after-used
      ignoreRestSiblings: false
      argsIgnorePattern: ^(_|(omit|ignore)[0-9]+)$
      caughtErrors: all
      caughtErrorsIgnorePattern: ^_$
  no-useless-return: error
  no-useless-computed-key: error
  no-useless-rename: error
  no-path-concat: error
  no-useless-concat: error
  prefer-template: error

  import/no-default-export: error

  react/jsx-filename-extension:
    - error
    - extensions:
        - .js
  react/no-unescaped-entities:
    - error
    - forbid:
      - '<'
      - '>'
      - '{'
      - '}'

  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn

  # flowtype/array-style-complex-type: [error, verbose]
  # flowtype/array-style-simple-type: [error, verbose]
  flowtype/boolean-style: [error, boolean]
  flowtype/define-flow-type: error
  flowtype/newline-after-flow-annotation: error
  flowtype/no-flow-fix-me-comments: [error, 'issue']
  flowtype/no-mutable-array: error
  flowtype/no-primitive-constructor-types: error
  flowtype/no-types-missing-file-annotation: error
  flowtype/no-unused-expressions: error
  flowtype/no-weak-types: [error, { any: false }]
  flowtype/require-compound-type-alias: off
  flowtype/require-readonly-react-props: error
  flowtype/require-types-at-top: error
  flowtype/require-valid-file-annotation:
    [error, never, { annotationStyle: block }]
  flowtype/require-variable-type:
    - error
    - excludeVariableTypes:
        const: true
  flowtype/spread-exact-type: off
  flowtype/type-id-match: [error, '^[A-Z][a-z0-9]*']
  # flowtype/type-import-style: [error, declaration]
  flowtype/use-flow-type: error
