parser: babel-eslint

plugins:
  - flowtype
  - prettier

extends:
  - airbnb
  - prettier
  - plugin:prettier/recommended

env:
  node: true
  browser: true

rules:

  prettier/prettier: error

  no-underscore-dangle: off
  eqeqeq: [error, smart]
  no-unused-expressions: off
  consistent-return: off
  no-dupe-keys: error
  react/jsx-closing-bracket-location: off

  import/prefer-default-export: off

  react/jsx-filename-extension: [error, { extensions: [.js] }]

  flowtype/define-flow-type: error
  flowtype/no-dupe-keys: error
  flowtype/no-flow-fix-me-comments: off
  flowtype/no-mutable-array: error
  flowtype/no-primitive-constructor-types: error
  flowtype/no-types-missing-file-annotation: error
  flowtype/no-unused-expressions: off
  flowtype/no-weak-types: off
  flowtype/require-exact-type: off
  flowtype/require-parameter-type: [off, { excludeParameterMatch: '^_[0-9]*$' }]
  flowtype/require-return-type: off
  flowtype/require-valid-file-annotation: [error, never, { annotationStyle: block }]
  flowtype/require-variable-type: off
  flowtype/sort-keys: off
  flowtype/type-id-match: [error, '^[A-Z][a-z0-9]*']
  flowtype/use-flow-type: error
